mysite/blog/urls.py
from django.conf.urls import url
from django.urls import path

from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<str:slug>/', PostDV.as_view(), name='post_detail'),
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    path('today/', PostTAV.as_view(), name='post_today_archive'),

    path('search/', SearchFormView.as_view(), name='search'),

    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),
]

mysite/bookmark/urls.py
from django.conf.urls import url
from django.urls import path

from bookmark.views import *

app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),

    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('change/', BookmarkChangeLV.as_view(), name='change'),
    path('update/<int:pk>/', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', HomeView.as_view(), name='home'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done', UserCreateDoneTV.as_view(), name='register_done'),

    path('bookmark/', include('bookmark.urls', namespace='bookmark')),
    path('blog/', include('blog.urls', namespace='blog')),
]

mysite/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
class Post(models.Model):
    title       = models.CharField('TITLE', max_length=50)
    slug        = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content     = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)
    owner       = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))
    
    def get_previous_post(self):
        return self.get_previous_by_modify_date()
    
    def get_next_post(self):
        return self.get_next_by_modify_date()
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)
    
    

mysite/bookmark/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)
    url_category = models.CharField(max_length=100, blank=True, null=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

mysite/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

mysite/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView
from blog.models import Post

from django.views.generic.edit import FormView
from blog.forms import PostSearchForm
from django.db.models import Q

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from mysite.views import LoginRequiredMixin

# Create your views here.
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 5

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'


class SearchFormView(FormView):
    form_class= PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        schWord = '%s' % self.request.POST['search_word']
        post_list = Post.objects.filter(Q(title__icontains=schWord) | Q(description__icontains=schWord) | Q(content__icontains=schWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = post_list
        
        return render(self.request, self.template_name, context)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content']
    initial = {'slug': 'auto-filling-do-not-input'}
    #fields = ['title', 'description', 'content']
    success_rul = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content']
    success_url = reverse_lazy('blog:index')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

mysite/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from mysite.views import LoginRequiredMixin

# Create your views here.
class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url', 'url_category']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(BookmarkCreateView, self).form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url', 'url_category']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(LoginRequiredMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

mysite/mysite/views.py
from django.views.generic.base import TemplateView

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

from django.contrib.auth.decorators import login_required

class HomeView(TemplateView):
    template_name = "home.html"

class UserCreateView(CreateView):
    template_name = "registration/register.html"
    form_class = UserCreationForm
    success_url = reverse_lazy("register_done")

class UserCreateDoneTV(TemplateView):
    template_name = "registration/register_done.html"

class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

mysite/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}post_all.html{% endblock %}

{% block content %}
<div id = "content">
    <h1>Blog List</h1>

    {% for post in posts %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {{ post.modify_date|date:"N d, Y" }}
        <p>{{ post.description }}<p/>
    {% endfor %}

    <br/>

    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}">PreviousPage</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

mysite/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}


{% block content %}
<div id = "content">
    <h1>Post Archives until {% now "N d, Y" %}</h1>

    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a>
        </li>
        {% endfor %}
    </ul>

    <br/>

    <div>
        <ul>
            {% for post in object_list %}
            <li>
                {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><string>{{ post.title }}<string></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

mysite/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}


{% block content %}
<div id = "content">
    <h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

    <div>
        <ul>
            {% for post in object_list %}
            <li>
                {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><string>{{ post.title }}<string></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

mysite/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month{% endblock %}


{% block content %}
<div id = "content">
    <h1>Post Archives for {{ month|date:"N Y" }}</h1>

    <div>
        <ul>
            {% for post in object_list %}
            <li>
                {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><string>{{ post.title }}<string></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

mysite/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}


{% block content %}
<div id = "content">
    <h1>Post Archives for {{ year|date:"Y" }}</h1>

    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a>
        </li>
        {% endfor %}
    </ul>

    <br/>

    <div>
        <ul>
            {% for post in object_list %}
            <li>
                {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><string>{{ post.title }}<string></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

mysite/blog/templates/blog/post_change_list.html
{% extends "base.html" %}

{% block title %}post_change_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Post Change - {{ user }}</h1>

    <table class="change-list">
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>

        {% for post in object_list %}
            <tr>
                <td>{{ post.title }}</td>
                <td>{{ post.description }}</td>
                <td>{{ post.owner }}</td>
                <td><a href="{% url 'blog:update' post.id %}">Update</a></td>
                <td><a href="{% url 'blog:delete' post.id %}">Delete</a></td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Post Delete</h1>

    <form action="." method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ? </p>
        <input type="submit", value="Confirm" />
    </form>

</div>
{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}
<div id="content">
    <h2>{{ object.title }}</h2>

    <p class="other_posts">
        {% if object.get_previous_by_modify_date %}
        <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post"> &laquo;--{{ object.get_previous_post }}</a>
        {% endif %}
        ||
        {% if object.get_next_by_modify_date %}
        <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post"> {{ object.get_next_post }}--&raquo;</a>
        {% endif %}
    <p/>

    <p class="date">{{ object.modify_date|date:"j F Y" }}<p/>
    <br/>

    <div class="body">
        {{ object.content|linebreaks }}
    </div>
</div>
{% endblock content %}

mysite/blog/templates/blog/post_form.html
{% extends "base.html" %}

{% block title %}post_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Post Create/Update - {{ user }}</h1>

    <form action="." method="post">
        {% csrf_token %}
        {% if form.errors %}
        <p class="errornote">Wrong! Please correct the error(s) below.</p>
        {% endif %}

        <p>This is a creation or update form for your post.</p>

        <fieldset class="aligned">
            <div class="form-row">
                {{ form.title.label_tag }} {{ form.title }}
            </div>
            <div class="form-row">
                {{ form.slug.label_tag }} {{ form.slug }}
            </div>
            <div class="form-row">
                {{ form.description.label_tag }} {{ form.description }}
            </div>
            <div class="form-row">
                {{ form.content.label_tag }} {{ form.content }}
            </div>
        </fieldset>

        <div class="submit-row">
            <input type="submit" value="Submit" />
        </div>    
        
        <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>
            

</div>
{% endblock %}

mysite/blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}

{% block content %}
<div id = "content">
    <h1>Blog Search</h1>

    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Search" />
    </form>

    <br/><br/>

    {% if object_list %}
        {% for post in object_list %}
            <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
            {{ post.modify_date|date:"N d, Y" }}
            <p>{{ post.description }}<p/>
        {% endfor %}
    {% elif search_term %}
        <b><i>Search Word({{ search_term }}) Not Found !</i></b>
    {% endif %}

</div>
{% endblock content %}

mysite/bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}bookmark_change_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Bookmark Change - {{ user }}</h1>

    <table class="change-list">
        <tr>
            <th>Title</th>
            <th>Url</th>
            <th>Url Category</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>

        {% for bookmark in object_list %}
            <tr>
                <td>{{ bookmark.title }}</td>
                <td>{{ bookmark.url }}</td>
                <td>{{ bookmark.url_category }}</td>
                <td>{{ bookmark.owner }}</td>
                <td><a href="{% url 'bookmark:update' bookmark.id %}">Update</a></td>
                <td><a href="{% url 'bookmark:delete' bookmark.id %}">Delete</a></td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

mysite/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Bookmark Delete</h1>

    <form action="." method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ? </p>
        <input type="submit", value="Confirm" />
    </form>

</div>
{% endblock %}

mysite/bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}bookmark_detail.html{% endblock %}


{% block content %}
<div id = "content">
    <h1>{{ object }}</h1>
    <h3>{{ object.url_category }}</h3>
    <ul>
        <li><a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
</div>
{% endblock content %}

mysite/bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}

{% block title %}bookmark_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Bookmark Create/Update - {{ user }}</h1>

    <form action="." method="post">
        {% csrf_token %}
        {% if form.errors %}
        <p class="errornote">Wrong! Please correct the error(s) below.</p>
        {% endif %}

        <p>This is a creation or update form for your bookmark.</p>

        <fieldset class="aligned">
            <div class="form-row">
                {{ form.title.label_tag }} {{ form.title }}
            </div>
            <div class="form-row">
                {{ form.url.label_tag }} {{ form.url }}
            </div>
            <div class="form-row">
                {{ form.url_category.label_tag }} {{ form.url_category }}
            </div>
        </fieldset>

        <div class="submit-row">
            <input type="submit" value="Submit" />
        </div>
        
        <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>

</div>
{% endblock %}

mysite/bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}bookmark_list.html{% endblock %}

{% block content %}
<div id="content">
    <h1>Bookmark List</h1>
    <ul>
        {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark.url_category }} - {{bookmark.title }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

mysite/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}Django Web Programming{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

<div id="header">
    <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
    {% if user.is_active %}
        <h4 class="welcome">Welcome, <strong>{% firstof usr.get_short_name user.get_username %}</strong> /
                    <a href="{% url 'password_change' %}">Change Password</a> /
                    <a href="{% url 'logout' %}">Logout</a>
        </h4>
    {% else %}
        <h4 class="welcome">Welcome, Anonymous /
                    <a href="{% url 'login' %}">Login</a> /
                    <a href="{% url 'register' %}">Register</a>
        </h4>
    {% endif %}
</div>

<div id="menu">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
    <li><a href="{% url 'blog:index' %}">Blog</a></li>
    <li><a href="#">Photo</a></li>

    <li><a href="#">Add&bigtriangledown;</a>
        <ul>
            <li><a href="{% url 'bookmark:add' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:add' %}">Blog</a></li>
	        <li><a href="#">Photo</a></li>
        </ul>
    </li>
    <li><a href="#">Change&bigtriangledown;</a>
        <ul>
            <li><a href="{% url 'bookmark:change' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:change' %}">Blog</a></li>
	        <li><a href="#">Photo</a></li>
        </ul>
    </li>

    <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
    <li><a href="{% url 'blog:search' %}">Search</a></li>
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
</div>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

mysite/templates/home.html
{% extends "base.html" %}

{% block title %}My Home Page{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div id="content_home">

    <div id="homeimg">
        <a href="/"><img src="{% static 'img/blockchain.gif' %}" style="height:256px;"/></a>
        <h4 style="margin: 0;">This is Django powered web site.</h4>
    </div>

    <hr style="margin: 5px 0;">

    <h2>Select Application</h2>

    <table id="applist">
        <tr>
        <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i><b></td>
        <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td class="Edit"><i><a href="#">Add</a></i></td>
        <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>

        <tr>
        <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i><b></td>
        <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td class="Edit"><i><a href="#">Add</a></i></td>
        <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>

        <tr>
        <td><b><i><a href="#">Photo</a></i><b></td>
        <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td class="Edit"><i><a href="#">Add</a></i></td>
        <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; 2018
</div>
{% endblock footer %}